### ISSUE TITLE
型名が長すぎる

### ISSUE THREAD

**Issue by sksat** [sksat/github-webhook-rs#78]
こういうやつ
https://sksat.github.io/github-webhook-rs/github_webhook/payload_types/struct.BranchProtectionRule.html
![2023-05-27_17-20_1](https://github.com/sksat/github-webhook-rs/assets/23310673/bb8bc072-50d5-49e0-8d4c-36bb6bcd7278)

それあそうではあるのだけど，正直長すぎる

**Comment by sksat** [comment]
問題は長すぎることよりも名前空間がフラットなことだな

**Comment by sksat** [comment]
`github_webhook::payload_types::Schema` の中身と同名の名前空間を切って，その prefix 付いてるやつはそこに押し込む，とかはややアリ

**Comment by sksat** [comment]
（とかまで考えると JSON Schema をエイヤしてもいい感は正直ややあるな）

**Comment by s-ylide** [comment]
名前が長いやつ、たまに中身が同じやつがいるので同一の名前空間で妥協しちゃったんですけど、ほんとは分けたいです

**Comment by s-ylide** [comment]
ある程度リファクタして見通し良くなったのでJSON Schemaから変換するようにした方がいいですね

**Comment by sksat** [comment]
わかる > 見通し良くなったので JSON Schema から変換

**Comment by s-ylide** [comment]
そういえばこの型はもとからこのくらい長いです jsonschemaからtsに変換するときに長くなってる
https://github.com/octokit/webhooks/blob/3e1d0a1870c7fca1c5e8d8277e5de2a9e5157806/payload-types/schema.d.ts#L484C11-L511

**Comment by sksat** [comment]
あ～～～

**Comment by sksat** [comment]
一旦どうしようもないということで閉じ
